name: Update EPG Data
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  filter_epg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run Filter Script
        run: python filter_epg.py

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated EPG Update"
          file_pattern: 'epg.xml'
